### ISSUE TITLE
Publish

### ISSUE THREAD

**Issue by natew** [motion/motion#102]
`flint publish`

Sharing flint apps so others can `import Button from 'flint-button'`.

Seems like it could be similar to `flint build`. Almost just point to the `.flint/.internal/out` directory.

We could have `flint build npm` which would build to `.flint/npm`, which their package.json main could point to `.flint/npm/main.js`.

As far as importing, it would automatically be installed into node_modules.

We'd need to bundle it before publish to export a usable React element.

Concat and wrap app with Flint.app('name', (Flint) => /* views and such */). Internals would need to be inside there. In the end it would return Main view. In fact this could be how all Flint apps are run. (Rather than sorta janky way we do now with tools).

We have some interesting stuff to think about with it. Such has how it looks for Flint.packages / Flint.internals. And passing props down into the exported component, what do we do about routes (disallow?).

But once we have this it becomes pretty awesome to share all sorts of cool stuff.

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
