### ISSUE TITLE
Isomorphic

### ISSUE THREAD

**Issue by natew** [motion/motion#157]
Meta topic for isomorphic rendering. I think this is important. Right now Flint weighs in production at:

40kb - react minified
50kb - flint + polyfills (bluebird/fetch) minified
+ app code size

This is not huge, but between download/parsing it doesn't feel immediate. I had a prototype isomorphic rendering demo set up at one point and it was working fine.

For a "real" version we would need:

- [x] Building out your app bundle in a way that is compatible with Node require
- [ ] Node server that understands your routes and outputs to HTML string
- [x] Protections against usage of window / incompatible npm modules
- [x] Hooks for document.title setting that works with isomorphic server

This would open us up to do a small hosting platform that lets you do `flint up` and have your app hosted & isomorphically rendered.

**Comment by natew** [comment]
A few new things I've realized:

- We can use jsdom to polyfill window/document and get basically full compatibility with that
  - See how jsdom is used here to do much the same https://github.com/darrylwest/mock-browser/blob/master/lib/MockBrowser.js
  - Can even pass in their actual index.html file to jsdom to get external scripts, potentially

- We can maintain a list of popular user-agents and their respective screen dimensions
   - Even for desktops we can at least provide a "just about" size, given maximum screen sizes typically
   - Also can pass down user-agent to jsdom https://github.com/tmpvar/jsdom/pull/225

With these two we have the base for really cool iso rendering.

Final considerations are data fetching. One thing we may want to do is detect any line in your view that returns a promise. This way we can automatically handle any async/await or fetch calls in your view.

```
view Main {
  let data

  fetch('/something').then(res => {
    data = res
  })

  // or
  let load = async () => {
    data = await fetch('/something')
  }

  load()

  <h1>{data}</h1>
}
```

In both these cases the line returns a promise (fetch and load). We could gather promises and wait for them to complete before rendering! If the user doesn't want this functionality they could either disable it globally, or just wrap it in a function that doesn't return a promise, easy.

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
