### ISSUE TITLE
Immutable

### ISSUE THREAD

**Issue by natew** [motion/motion#158]
Another meta topic to discuss using immutable data. Current libraries:

- https://github.com/facebook/immutable-js
- https://github.com/arqex/freezer

Upsides would be huge if we could get it to work, and it doesn't have to be enforced, it could be an optional plugin or something that Flint auto detects.

As a first class part of Flint we'd have to work really hard to match the JS api's. But if we got that working we'd have some huge upsides: a big upgrade to speed in nearly every area, and avoiding some really frustrating code that you have to write now to "logic" your way through props (or use some sort of deep-equals library).

Opening this to track the topic.

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
