### ISSUE TITLE
Babel 6

### ISSUE THREAD

**Issue by natew** [motion/motion#160]
Opening a ticket to track this, want to do this probably before launch because it removes out last "hacky" thing in all of Flint (at least in terms of compiling).

**Comment by natew** [comment]
Blocked until https://phabricator.babeljs.io/maniphest/query/OPmW7DgWqDc6/#R

**Comment by natew** [comment]
Unblocked

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
