### ISSUE TITLE
The Great Propposal

### ISSUE THREAD

**Issue by natew** [motion/motion#174]
Props are a bit funky atm:

![image](https://cloud.githubusercontent.com/assets/12100/11412911/d4926008-9397-11e5-8b70-9e41ecfc6fa6.png)

Using `view.props.xyz` for everything is definitely a relic from React. It's not a bad pattern, it just feels super verbose and not very well through of. Lets not even mention on.props and reacting to props, etc.

So heres the propposal. If you are scared of new syntax, run away! There be sharks here...

```js
view Hello {
  prop first : string = 'Liron'
  prop last : string = 'Cammerata'

  <h1>hello {first} {last}</h1>
}
```

Now I threw in types because of how beautifully this would let us use them. Lets ignore them for now.  The way I see it is this:

Pros | Cons
------------ | -------------
Obvious | Is non-standard
Supports default values | Default values deter from what variable declarators normally do
Supports types | What happens on.props
Just variables | Looks like declarator, acts slightly differently (though "declares" props)
"Declarative" | 

One esoteric argument I can see for it is if we're going to be a DSL we may as well be a good one. In that, if we're making the `view` a thing, we should have an equally good `prop` answer since props are one of the biggest thing views deal with (half of the input/output equation). So perhaps the weirdness of new syntax would actually be a smaller con compared to the huge pro of this fixing React's super-odd PropTypes object stuff.

Fleshing out the example

```js
view Hello {
  prop exclaim : ?string = '!!!' // optional + default
  prop first : string // no default
  prop last : ?string // optional

  function greet() {
    return `Hello ${first} ${last}${exclaim}`
  }

  <h1>{greet()}</h1>
}
```

TODO: make example showing on.props and changing.

**Comment by natew** [comment]
Adding to this, my thoughts on the props changing over time are that they act much like styles/render. So we essentially have windows inside a view.

**Comment by ncammarata** [comment]
converted https://github.com/flintjs/examples/tree/master/timer to this. I love it more every day

**Comment by natew** [comment]
Right now it's pretty dumb in compiling, what we could do is track it in babel.

We should

- Only allow props first in view
- Disallow interspersing props with variables or anything else
- Once thats done, we can basically wait for "something else" to come after a prop, and assume thats the end of props. Then we can batch all the `on.props` into one.

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
