### ISSUE TITLE
Refactor bridge to allow plugins

### ISSUE THREAD

**Issue by natew** [motion/motion#180]
Jumping into the latest atom/bridge changes and it looks awesome, but also getting confusing because we have such a hacked together set of standards for socket messages.

We're probably at the point where we can win a lot by doing our next "big arch upgrade" now and making the bridge system more standardized and pluggable.

Needs to allow for:

- Sending to browser
- Sending to editor
- Standards for structure of data
- Sharing libraries on all sides for handling messaging
- Same dir/filenames in each side for easy navigation

**Comment by natew** [comment]
@steelbrain

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
