### ISSUE TITLE
Fast "local production mode"

### ISSUE THREAD

**Issue by liron00** [motion/motion#187]
Flint's normal dev server behavior has some performance penalty, especially with browsers other than Chrome. Have a dev setting that is closer to production performance, in exchange for losing some of the live updating.

**Comment by natew** [comment]
We could have `--prod` flag for CLI, which doesn't need to do anything but set environment to production. This would make React faster. We could keep hot reloads or not. Wouldn't need to minify I don't think.

**Comment by natew** [comment]
Ok with new flint build --watch i have a solution for this

For now you can do `flint build --watch` in a separate tab and then run a static server and just have that open. It's now just as fast as running your app normally which is cool.

But I realize now I could easily fork a child process (maybe under a flag `flint --withprod`). Now you'd have flint running your app and building your app at the same time with very little extra work on my end. You could hit one port for dev and another for prod. I think this is realistically only 1-2hr work more :)

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
