### ISSUE TITLE
Let Flint.router.go navigate off the site via absolute URLs

### ISSUE THREAD

**Issue by liron00** [motion/motion#189]
`Flint.router.go("http://yahoo.com")` currently doesn't the expected behavior of redirecting to yahoo.com.

**Comment by natew** [comment]
Not hard to support in the simplest case (detect starts with 'https?://'), @ncammarata does this seem like generally ok to do?

**Comment by ncammarata** [comment]
I would normally say use window.location for remote, but its so useful to have a single Link view that calls .go that I think this is fine. Let's go for it.

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
