### ISSUE TITLE
Visualize codename Trinity in Compiler

### ISSUE THREAD

**Issue by ncammarata** [motion/motion#197]
I'll build the same thing in Atom, and browser should have one. Basically we should always be able to see whats going between everything

**Comment by natew** [comment]
?log=socket gives us everything thats going over, but we can have a higher discussion on it. we should not build out custom UI for this stuff, just use console/terminal as we have that in all three areas (unless we can justify some huge leap given to us by UI).

**Comment by natew** [comment]
Problem is if bridge breaks, then it wont visualize the break properly, and if show it in one area then it will be prone to showing things wrongly when they break.

**Comment by ncammarata** [comment]
yeah terminal is fine. Each thing should have its own logging system, but we should also be able to see, from the compiler, the connections nicely. As in should be able to say "show me editor -> compiler" or "browser <-> compiler" somehow and have it filter for that. Then each client should have a log that can be used for testing reconnections

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
