### ISSUE TITLE
Throw errors on obviously bad statements in onEvents

### ISSUE THREAD

**Issue by natew** [motion/motion#211]
```
view Main {
  <button onClick={x = 1}>click</button>
}
```

We may not want to do runtime checking to see if its a function only, not sure why but perhaps undefined/null/false maybe valid as a "not callback-able" type.

Anyway in Babel we could detect this and warn.

**Comment by ncammarata** [comment]
why was this closed?

**Comment by natew** [comment]
It's not technically a bad statement, there are definitely use cases where this could be used. This was the only questionable one I closed though, I can keep it open. It's just high work for low payoff, and tricky to implement in a way that may not actually be wrong for some use cases.

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
