### ISSUE TITLE
Nice style errors

### ISSUE THREAD

**Issue by ncammarata** [motion/motion#23]
```js
$button {
  color: 'blue'
}
```

should bring up 'did you mean $button = {?' or something similar. This would likely require regex in the compiler, but that is fine because its a syntax err

```js
$button {
  font-size: 16
}
```

should bring up `flint styles are camelCase. Did you mean fontSize?

I've seen users make both mistakes many times and it's a good opportunity for some really nice errors

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
