### ISSUE TITLE
Examples need a lot of love

### ISSUE THREAD

**Issue by natew** [motion/motion#233]
The kit one for example is really simple, not indented well, uses comment style differently than elsewhere, and generally could be a lot more diverse (use arrays to show combining styles).

I'm sure we can do this for most of them, and add a README to guide people. Not just a half day of sort of editing a few but really dedicating some time to making them great.

**Comment by natew** [comment]
I do know we want to have examples on the site, but having a repo is important as well. We can eventually turn the repo into site examples.

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
