### ISSUE TITLE
Consider removing auto wrapping elements

### ISSUE THREAD

**Issue by natew** [motion/motion#238]
And only doing it when theres side by side elements.

**Comment by natew** [comment]
@ncammarata @liron00 looking for thoughts here.

The basics are that right now we wrap every view with an outer container. UNLESS they contain an element that is the same name as the view. It's definitely a bit weird

```
// this gets wrapped with an outer div
view MyTitle {
  <h2 yield />

  $ = {} // this styles the outer div
  $h2 = {}
}

view Button {
  <button /> //doesnt get wrapped, this matches view
}

view OtherButton {
  <button root /> // root attribute makes it not wrapped
}
```

We also support multiple top level elements, which in React would always need to be wrapped (maybe in the future React not though)

```
view Multi {
  <button />
  <other />
  
  $ = {} // this styles outer
}
```

The change would be to remove the wrapping for all view except the last type (Multi, because you cant). That would mean:

- No more need for "root" prop
- No more weird "if it matches the name of view" thing (this could be removed too in current way)

**Comment by natew** [comment]
One good point is styling children: If views autowrap the styling will always go to the wrapper! Could lead to bad practice or just generally a lot of `root` attributes.

**Comment by jiggity** [comment]
I hadn't realized having a lowercase DOM element same as the capitalized class wasn't wrapped.   This seems like a potential confusing case where behavior doesn't work as expected.

Having to know special properties like:
- When things are wrapped and not
- Relationship between styling: $Button={} in the parent and $={} in the Button class
- Lowercase DOM element acts as the root element if it's present

One potential solution is to standardize the naming of the root element as part of writing a proper React class

view Button {
    <root>
       <child />
       <child />
   </root>
}

**Comment by jiggity** [comment]
```
view Button {
     <root>
        <child />
        <child />
        <child />
     </root>
}

```

**Comment by liron00** [comment]
Has anyone identified any downsides to *not* wrapping a view in an outer element?

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
