### ISSUE TITLE
CSS is selecting children when it shouldn't

### ISSUE THREAD

**Issue by natew** [motion/motion#239]
```js
view Main {
  <Text>hello</Text>
  <Sub>not red</Sub>

  $Text = { color: 'red' }
}

view Text {}
view Sub { <Text /> }
```

Red shouldn't be on Sub. But our selector `.MainView .Text` gets it. We should

- Pass down the class of parent to the child views.
- Apply that class child wrapper node
- Then style like this `.MainView.Text` not `.MainView .Text`

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
