### ISSUE TITLE
Can't style subview syntax

### ISSUE THREAD

**Issue by natew** [motion/motion#240]
```
view Main {
  <Sub.What />
  $Sub.What = {} // ?
}
```

**Comment by natew** [comment]
@ncammarata thoughts?

Dash tags you can style each half <name-other>, but when we remove the weird usage of them now not sure how we handle that.

**Comment by ncammarata** [comment]
so a selector for "style all the things that have the tag input" even if they're named differently?

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
