### ISSUE TITLE
Nested Repeats

### ISSUE THREAD

**Issue by ncammarata** [motion/motion#241]
```js
<div repeat={[1,2,3]}>
  <div repeat={[2,3,4]}>
    how do I show x * y here?
  </div>
</div>
```

**Comment by natew** [comment]
Need to have function inners or named repeats.

**Comment by ncammarata** [comment]
I thought fn inners worked at one point, but I couldn't get them running. Should they be working or do we need to build it?

**Comment by natew** [comment]
Not sure on this one actually would need to investigate.  A grep for `repeat` should be easy to explore.

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
