### ISSUE TITLE
Pretty output by default

### ISSUE THREAD

**Issue by ncammarata** [motion/motion#242]
people want to see clean output and minifying in dev doesn't help much

**Comment by natew** [comment]
It's not minified it preserves line numbers for error messages. 

Ideal solution is to use a source map reverser in the browser so you have both. But that's a ticket somewhere already.

**Comment by natew** [comment]
https://github.com/mozilla/source-map/

**Comment by natew** [comment]
Closing dup https://github.com/flintjs/flint/issues/163

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
