### ISSUE TITLE
textbox sync number?

### ISSUE THREAD

**Issue by ncammarata** [motion/motion#243]
```js
view Main {
  let num = 5

  <input sync={num} />
}
```

should the input sync the int if only numbers are entered? should only numbers be allowed? up for discussion

**Comment by liron00** [comment]
Can implement sync as an arbitrary Derivable object and call its get and set. The int conversion stuff would be one of many cool things you can do by picking the appropriate Derivable.

**Comment by natew** [comment]
To me sync is an underpowered attribute somehow. Goes back to wanting some sort of `set` function that you can pass a variable to and have it update. Then you could just write

```
<input onChange={e => set(x, e.target.value)} />

let sete = x => e => set(x, e.target.value)

<input onChange={sete(x)} />
```

Now you have a lot of power, can do all sorts of stuff with functions.

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
