### ISSUE TITLE
Smarter static styles (in imported files)

### ISSUE THREAD

**Issue by natew** [motion/motion#246]
People will want to put styles into functions, separate files and import, etc. We should still be able to statically extract them.

Two options: in the long run we definitely want something more akin to Flow that actually understands runtime code so we can extract / optimize anything. This gives us tons of other upsides as well, but is very hard.

We could also have something like this:

```
var x = Flint.style({ background: 'red' })
```

This could clue us in anywhere that it's a style and perhaps give us enough to work with.

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
