### ISSUE TITLE
Use proxy for modifying views at runtime in console

### ISSUE THREAD

**Issue by ncammarata** [motion/motion#247]
https://twitter.com/addyosmani/status/687657702122717188

We can use a mixture of this and the state inspector to allow you to change and introspect views at runtime

If I have 

```js
view Greeting {
  let name = "nick"
  <input sync={name} />
}
```

I should be able to pin this in my inspector, then open console and run
```js
views[0].name = 'Bowie'
```

we can use Proxy to get the modified variable and run view.set on that, leading to a great dev experience

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
