### ISSUE TITLE
Configurability

### ISSUE THREAD

**Issue by natew** [motion/motion#278]
Given recent advances in React compatibility, configuration has become a "next up" thing.

We have a unique build system in that webpack is used for some stuff, the rest just goes through babel. So in terms of "loaders" may need to figure out how to do it differently. We may just want webpack to basically handle concatting together things, and leave all the rest to our pipeline. This way it works the same for view/non-view files.

Some things configuration needs to cover:

### Environments

Basically you have development and production. But perhaps you want other ones. And you probably want to be able to run your flint server in dev/production mode.

May want to do things to assets differently in production. Run image-min, minify css, etc.

Also probably need a way to provide variables to apps based on environment. So if it's going to production I can say "provide `PRODUCTION=true` to app".

Some of this could be done by default, but I think eventually especially with supporting the diverse React stacks we'll need to expose a few things at least.

### Configuring webpack

In the specific case of importing a React app, we'd need to be very clear that webpack *only* handles stuff you "import" locally. But in that case we could just let people drop in a webpack config file and we merge it with the one we use internally.

Hurdles for this right now are

 - Where to put webpack config (this goes with environment too)
 - Flint auto-installing config files dependencies
 - Flint merging the config properly
 - Problems relating to the fact we run webpack from `.flint/.internal`, but providing configs access (exclusively?) to app folder not internal folder

### Configuring babel

Same as above, but all files run through Babel. We are also on 5 until async/await gets a bit better in 6, so this probably need to hold off anyway.

### Other hooks

Some ones I can think of without too much depth...

- General prebuild/postbuild script support (npm package.json scripts integration?)

**Comment by natew** [comment]
Quite a few of these have been completed in the new configure release. Just need to add webpack support.

Babel works, environments work, needs docs.

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
