### ISSUE TITLE
Hot reload static assets

### ISSUE THREAD

**Issue by natew** [motion/motion#28]
This actually probably easier than it sounds:

- [ ] Gulp pipeline for static assets
- [ ] Gulp sends bridge message to reload on asset change
- [ ] Can we just trigger a "reload" in the page somehow? If not, some simple way to force the browser to check for new assets

Keep in mind: assets could be used in all sorts of ways. <img picture />, <link src />, etc. So should stay really generic and simple if possible.

**Comment by natew** [comment]
Example:
https://github.com/cortesi/devd/blob/master/livereload/static/client.js#L280

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
