### ISSUE TITLE
Inspector: empty fields have incorrect textbox positions

### ISSUE THREAD

**Issue by ncammarata** [motion/motion#282]
https://v.usetapes.com/fWBHcjc0jn

**Comment by AriaFallah** [comment]
@ncammarata unrelated to the bug...what are you using to modify the state?

**Comment by ncammarata** [comment]
![image](https://cloud.githubusercontent.com/assets/204989/12545726/a6b9075e-c2f9-11e5-8280-d5f92268ddb8.png)

**Comment by natew** [comment]
@ncammarata 
![image](https://cloud.githubusercontent.com/assets/12100/12636845/6888fc70-c545-11e5-9dfb-28033f618a74.png)

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
