### ISSUE TITLE
Remove unnecessary pipeFn calls in Gulp Pipeline

### ISSUE THREAD

**Issue by ncammarata** [motion/motion#289]
We should update the gulp pipeline to remove the long list of pipeFn calls that are currently necessary to go around a bug in Gulp

**Comment by AriaFallah** [comment]
![pipe](https://cloud.githubusercontent.com/assets/9424976/12569812/35fffe4e-c3a0-11e5-8de8-19365861f05a.jpg)

I've heard these are pretty good at cleaning pipes.

**Comment by natew** [comment]
Gulp 4 branch should do it

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
