### ISSUE TITLE
Proposition, views starting with _ aren't global

### ISSUE THREAD

**Issue by ncammarata** [motion/motion#312]
often I'm working in a view say
```view Sidebar.Nav.Item```

and I want to have an Icon view

I'd rather not write

```view Sidebar.Nav.Item.Icon```

and I also don't want a global Icon view.

How about ```view _Icon```

**Comment by ncammarata** [comment]
currently it's actually an invalid view name

**Comment by natew** [comment]
So that view is then scoped to the current file only?

`private` is a future reserved word. Maybe controversial but we could have:

`private view Icon {

}`

**Comment by natew** [comment]
Actually, views should return themselves from when they are created (if they don't yet it's a 1 line change). So compiles to:

```Flint.view('Name', () => {})```

So we could perhaps do "no-name" views:

```
const Name = view {

}
```

Flint would recognize that this view's unnamed and not add it to global, you could then use it as a variable.

Also lets you do exported views. Which we could allow using `export view` anyway, or `export const Name = view {}`

**Comment by AriaFallah** [comment]
@natew I like this idea a lot. How would you decorate these views?

**Comment by natew** [comment]
@AriaFallah 

```js
const Name = decorator(view {

})
```

**Comment by AriaFallah** [comment]
@natew haha that makes a lot of sense thanks.

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
