### ISSUE TITLE
`static` fields in classes

### ISSUE THREAD

**Issue by freiksenet** [motion/motion#316]
Used often for Relay, eg https://facebook.github.io/relay/docs/guides-routes.html#content

Currently I have to do stuff like that:

```js
class UploadRoute extends Relay.Route {}
UploadRoute.routeName = 'UploadRoute'
UploadRoute.queries = {
  viewer: () => Relay.QL`
    query {
      viewer
    }
  `,
}
```

This is supported by Babel, it actually doesn't give an error, but static fields just disappear somewhere.

**Comment by natew** [comment]
Could you configure babel through our config.js or does that not work?

We're still on `5.8` actually a `6` upgrade is coming soon. I could enable it but we are hesitant to go too early stage on things by default.

**Comment by freiksenet** [comment]
I couldn't figure how to configure that part in motion config %)

I've tried

```
babel: {
    optional: ["es7.classProperties"],
}
```

**Comment by natew** [comment]
Oh good point, because it's babel 5. I can test this myself. We are moving to 6 soon as well which should be better for this.

**Comment by natew** [comment]
Btw we are looking into this, strange things happening it's just stripping out that stuff. Should have fix in next day or so.

**Comment by steelbrain** [comment]
After some digging I found the buggy line,
 ```
metadata: { group: 'builtin-trailing' },
```
in packages/transform/src/file.js
If we change that to `metadata: {}`, everything works as expected

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
