### ISSUE TITLE
Missing displayName causes bad Relay warnings

### ISSUE THREAD

**Issue by freiksenet** [motion/motion#317]
I get warnings from Relay like the following

```
Warning: RelayContainer: Expected prop `picture` supplied to `` to be data fetched by Relay. This is likely an error unless you are purposely passing in mock data that conforms to the shape of this component's 
```

Usually they are helpful, but it seems that Relay can't pick up displayName from Flint view, which makes it unable to show which component has an error.

**Comment by natew** [comment]
Hm, adding a name to our hot reload proxy component in development as well. Perhaps we should have decorators just wrap below the proxy, but I'd have to test that and see what happens.

**Comment by natew** [comment]
This should be fixed in latest release, lmk

**Comment by steelbrain** [comment]
No longer valid since v1.1.0
