### ISSUE TITLE
repeat={collection as x} syntax?

### ISSUE THREAD

**Issue by AriaFallah** [motion/motion#334]
In a nested loop how do you differentiate between the inner and outer collection you're repeating over considering that the item is called `_`?

Is there any support for naming the element you're iterating over?

**Comment by natew** [comment]
We're in the process of basically de-risking motion as much as possible, the repeat helper is one of those tricky ones where it's really nice but adding custom syntax to it makes it too risky.

It's something we've talked about quite a bit in fact I think there may be another ticket here on it (not sure). But we should continue exploring what to do.

**Comment by AriaFallah** [comment]
@natew I'm all for derisking it. Do you have any idea when the react-compat branch will be ready?

**Comment by natew** [comment]
It's getting there. I'll add basic docs to the pr later today
