### ISSUE TITLE
Release a 1.0

### ISSUE THREAD

**Issue by steelbrain** [motion/motion#349]
We have been using the new motion for quite some time and it seems to be working good, just some minor bugs in [pundle](https://github.com/motion/pundle)

- [x] Release a 1.0 of pundle
- [x] Merge #340 in
- [x] Move `node_modules` and `package.json` from `.motion` to `$root`

**Comment by natew** [comment]
Awesome. Talked with @AriaFallah today too about potentially helping you with doing some documentation. If i get some time today I could whip up a couple logos too for fun.

**Comment by natew** [comment]
We can probably merge vorpal into master as well at this point. Also, one final thing before 1.0 would probably be to move node_modules/package.json to root because then we will be much more compatible / standard.

**Comment by steelbrain** [comment]
I moved it into `.motion` to keep things cleaner, but I can see the side effects like plugins like eslint not detecting their config modules (unless we link it up to the root), I've added it to the checklist in the top comment

**Comment by steelbrain** [comment]
Fixed by https://github.com/motion/motion/releases/tag/v1.1.0
