### ISSUE TITLE
Directory for static files

### ISSUE THREAD

**Issue by liron00** [motion/motion#352]
Right now the rule is to put static files in .motion, but we should conceptually separate the two concepts of "static root" and "motion internal directory"

**Comment by steelbrain** [comment]
The idea sounds nice. We could keep the `state.json` and `config.json` in `.motion` and move other things like favicon and html files to the new static folder.

What should we name our static folder though? `static` or `public` or `public_html`? Thoughts @natew @ncammarata @liron00 ?

**Comment by natew** [comment]
Yea I think static could be nice. Could also be configurable through config.json (`{ static: './static' }`)

**Comment by steelbrain** [comment]
`static` it is then, @liron00 also voted in favor of it in slack conversation. I also like the idea of it being configurable!

**Comment by steelbrain** [comment]
Fix is up in #377
