### ISSUE TITLE
Publish v2.0.0

### ISSUE THREAD

**Issue by natew** [motion/motion#366]
We have issues with motion@latest at times, for some reason 1.4.1 is published and latest is 2.0.0, can we publish new versions to fix?

**Comment by steelbrain** [comment]
It's already there
<img src="https://cloud.githubusercontent.com/assets/4278113/16550830/fa1f3dfc-4164-11e6-9ee7-5bf6b88ab1f2.png">

**Comment by natew** [comment]
Oh ok. It was showing outdated for some reason when running npm outdated

On Sunday, July 3, 2016, Steel Brain <notifications@github.com> wrote:

> Closed #366 <https://github.com/motion/motion/issues/366>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/motion/motion/issues/366#event-711600441>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAAvRLPdAEzlFtIVq3xcY9wnrh5sf8krks5qSIvLgaJpZM4JD9wN>
> .
>


-- 
natewienert.com @natebirdman <http://twitter.com/natebirdman>
